# theme: jekyll-theme-minimal
# title: title_from_conf.yml
# layout: default
layout: full



docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html